name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: rustfmt check
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo fmt --all --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: clippy check
        run: cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
      - name: docs check
        run: cargo doc --workspace --no-deps --all-features --document-private-items

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@nightly
      - name: test
        run: cargo test --workspace --all-features
